name: Code Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    name: 'Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Unit Tests
        run: yarn run test

      - name: TypeCheck
        run: yarn run typecheck

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build
